### ISSUE TITLE
Introduce Changelog to track versioning.

### ISSUE THREAD

**Issue by apolishch** [lanetix/node-bookshelf-soft-delete#7]

**Comment by apechimp** [comment]
I normally just write a commit message with a version number as a tittle and a summary of the commits since the last rev as the body. Then I tag that commit with the version number. Github creates releases based on tabs so that becomes the change log. Does that sound good for here or do you want to do something else?

**Comment by apechimp** [comment]
See https://github.com/lanetix/node-bookshelf-soft-delete/releases/
